migrate existing /var/vcap/store/[server,agent] to /var/vcap/store/k3s-datadir
migrate /var/vcap/store/agent to /var/vcap/store/k3s-datadir
migrate /var/vcap/store/server to /var/vcap/store/k3s-datadir
+ move set -e earlier to fail fast

diff --git a/jobs/k3s-agent/templates/bin/pre-start.erb b/jobs/k3s-agent/templates/bin/pre-start.erb
--- a/jobs/k3s-agent/templates/bin/pre-start.erb
+++ b/jobs/k3s-agent/templates/bin/pre-start.erb
@@ -7,10 +7,16 @@ export JOB_DIR="/var/vcap/jobs/k3s-agent"
 # Setup ssh env vars
 ${JOB_DIR}/bin/setup-user-env
 
-# persistent dir for k3s datadir
-#FIXME: rename existing /var/vcap/store/k3s-agent to k3s-datadir if exists
-mkdir -p /var/vcap/store/k3s-datadir
+#FIXME: exit on error earlier
+set -e
 
+# rename existing /var/vcap/store/k3s-agent to k3s-datadir if exists
+if [ -d /var/vcap/store/k3s-agent ]; then
+  # Note: potential remaining leaky open files should not be affected by the mv, according to https://unix.stackexchange.com/a/29227/381792
+  mv --no-target-directory /var/vcap/store/k3s-agent /var/vcap/store/k3s-datadir
+fi
+# persistent dir for k3s datadir
+mkdir -p /var/vcap/store/k3s-datadir
 
 # Prepare a persistent directory so /etc/rancher/node paswword file is kept on bosh recreate
 mkdir -p /etc
@@ -24,7 +30,6 @@ cp /var/vcap/packages/k3s-images/k3s-airgap-images-amd64.tar.gz /var/vcap/store/
 gunzip -f /var/vcap/store/k3s-datadir/agent/images/k3s-airgap-images-amd64.tar.gz
 
 
-set -e
 # Set overlay IP
 OVERLAY_IP="<%= spec.ip %>"
 <% if spec.ip != spec.networks.marshal_dump.values.first.ip %>
diff --git a/jobs/k3s-server/templates/bin/pre-start.erb b/jobs/k3s-server/templates/bin/pre-start.erb
--- a/jobs/k3s-server/templates/bin/pre-start.erb
+++ b/jobs/k3s-server/templates/bin/pre-start.erb
@@ -5,9 +5,15 @@ export JOB_DIR="/var/vcap/jobs/k3s-server"
 # Setup ssh env vars
 ${JOB_DIR}/bin/setup-user-env
 
+#FIXME: exit on error earlier
+set -e
 
+# rename existing /var/vcap/store/k3s-server to k3s-datadir if exists
+if [ -d /var/vcap/store/k3s-server ]; then
+  # Note: potential remaining leaky open files should not be affected by the mv, according to https://unix.stackexchange.com/a/29227/381792
+  mv --no-target-directory /var/vcap/store/k3s-server /var/vcap/store/k3s-datadir
+fi
 # persistent dir for k3s datadir
-#FIXME: rename existing /var/vcap/store/k3s-agent to k3s-datadir if exists
 mkdir -p /var/vcap/store/k3s-datadir
 
 # Prepare a persistent directory so /etc/rancher/node paswword file is kept on bosh recreate
